### PR TITLE
Lodash Big Up

### PR DESCRIPTION
**Pull request by KINFOO**
PLTFRS-5643: New `lodash`

https://issues.sierrawireless.com/browse/PLTFRS-5643
https://confluence.sierrawireless.com/pages/viewpage.action?spaceKey=AVENG&title=Migrate+to+lodash

### CODE REVIEW

**Comment by jlescot** [comment]
If you are adventurous, you could improve the only use of `lodash` function:

```
function isRuuid(ruuid) {
    return _.isString(ruuid) && (ruuid.indexOf(PREFIX) === 0);
}
```

could be rewritten into:

```
function isRuuid(ruuid) {
    return _.startsWith(ruuid, PREFIX);
}
```

**Review by jlescot — APPROVED** [review]
A minor remark, otherwise LGTM 👍

**Comment by KINFOO** [comment]
@jlescot
God Game

**Comment by KINFOO** [comment]
``` sh
$ node
> lodash = require('lodash')
# ...
> lodash.startsWith(null, 'h')
false
> lodash.startsWith('horse', 'h')
true
```

It is `null` proof!

**Pull request merged**
